polar:
  greeting: Welcome to the local book catalog!!!

spring:
  application:
          name: catalog-service
  #profiles:
     #active: testdata
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://configserver:8888
      request-connect-timeout: 5000 #ms
      request-read-timeout: 5000 #5ms
      fail-fast: false #In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  devtools:
    restart:
        trigger-file: .reloadTrigger
        poll-interval: 400ms
        quiet-period: 1ms

management:
  endpoints:
    web:
      exposure:
        include: refresh

server:
    port: 9001
    tomcat:
        connection-timeout: 2s
        keep-alive-timeout: 15s
        threads:
            max: 50
            min-spare: 5
            

